<?php
/***************************************************************************
 *                          lang_faq.php [portuguese_brazil]
 *                                -------------------
 *     begin                : Wed Nov 01 2006
 *     copyright            : (C) 2008 Grupo Suporte phpBB
 *     email                : suporte@suportephpbb.org
 *
 *     $Id: lang_faq.php,v 1.0 2008/02/27 17:15:00 Suporte phpBB Exp $
 *
 ****************************************************************************/

/****************************************************************************
 * Traduzido por:
 * Suporte phpBB - <http://www.suportephpbb.org/>
 ****************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

$faq[] = array("--","Sobre o <i>login</i> e o <i>registro</i>");
$faq[] = array("Porque é que não consigo entrar no fórum?", "Ainda não se registrou? Você deve se registrar de forma a poder entrar no fórum. Você foi banido do fórum? Surgirá uma mensagem se tal aconteceu. Caso haja um banimento, você deve contatar o administrador do fórum e perguntar o porquê se não souber a razão. Caso esteja registrado e não se encontre banido e mesmo assim não consiga entrar, verifique novamente se o seu nome de usuário e senha estão corretos. Normalmente é esse o problema. Caso não saiba mesmo o que possa ser, e não seja nenhuma das razões anteriormente descritas, contate o administrador do fórum pois pode haver alguma configuração errada no sistema.");
$faq[] = array("O registro é obrigatório para utilizar este fórum?", "Poderá não ser necessário. Está inteiramente ao critério do administrador do fórum se é necessário o registro, para que seja possível aos usuários o envio de suas mensagens. Contudo, o registro lhe dá acesso a funções adicionais e possivelmente a fóruns que não estão disponíveis a visitantes. Alguns exemplos são o uso e definição de avatares, uso de mensagens particulares, enviar e receber emails entre diversos usuários, inscrição em grupos de usuários, etc. São necessários apenas alguns segundos para se fazer o registro, então é recomendável que o faça.");
$faq[] = array("Por que entro automaticamente no fórum?", "Se não assinalar <i>Lembrar minhas informações</i>, você não entrará automaticamente da próxima vez que visitar o fórum. Isto evita o uso abusivo da sua conta por outra pessoa. Para se manter online e não necessitar escrever o seu nome de usuário e senha, assinale esta caixa quando entrar. Isto não é recomendável caso acesse o fórum através de um computador compartilhado por outros usuários, ou seja, bibliotecas, cefé internet ou cyber café, universidades, etc.");
$faq[] = array("Como posso ocultar o meu nome de usuário da lista de usuários online?", "Em seu perfil há uma opção nomeada <i>Ocultar seus status online</i>. Se selecionar <i>sim</i>, apenas você e o administrador poderão ver que está online. Passará a ser considerado pelo sistema do phpBB2 como um usuário invisível.");
$faq[] = array("Esqueci a Senha!", "Não entre em pânico! Você deve solicitar uma nova senha. Apesar da sua senha não poder ser recuperada pela administração do fórum, pode no entanto ser feito como que se nunca a tivesse registrado, ou seja, como que se estivesse entrando pela primeira vez. Para fazer isto, vá para a página de login e em seguida clique em <u>Esqueci a senha</u>, e seguindo às instruções, voltará a entrar no fórum em questão de minutos.");
$faq[] = array("Registrei-me mas não consigo entrar!", "Primeiro, verifique se está escrevendo o nome de usuário e senha corretamente. Caso estejam corretos, então uma entre duas coisas podem estar acontecendo - Se a função COPPA estiver ativa no fórum e você clicou em <u>Aceito estes termos e tenho menos de 13 anos de idade</u> ao se registrar, você terá que seguir às instruções que recebeu. Se este não é o seu caso, será que o seu registro está ativado? Alguns administradores preferem que o registro de novos usuários seja ativado através de um email, para que possa definitivamente acessar o fórum. Caso isso aconteça, quando você se registrou, deve ter sido informado se a ativação seria ou não necessária. Se recebeu o email, então siga às suas instruções. Se não recebeu o email, será que o endereço de email escrito é válido? Uma das razões para a ativação ser feita é para reduzir o número de abusos do sistema por usuários disfarçados ou passando pelo anonimato. Se você tem certeza que o endereço de email que forneceu é válido e correto, então tente contatar o administrador do fórum.");
$faq[] = array("Registrei-me anteriormente mas não consigo mais entrar!?", "As razões mais prováveis são: Você escreveu um nome de usuário ou senha incorretos (veja o email enviado quando se registrou inicialmente), ou o administrador poderá ter excluído o seu registro por algum motivo. É comum administradores excluírem registros de usuários que nunca enviaram mensagens, para reduzir o tamanho do banco de dados. Tente registrar-se novamente e participar das discussões do fórum.");


$faq[] = array("--","Sobre as <i>preferências</i> e <i>configuração de usuários</i>");
$faq[] = array("Como altero a minha configuração?", "Toda a sua configuração (após o registro) é salva no banco de dados. Para alterá-la, clique em <u>Perfil</u> (normalmente no topo da página, dependendo da template em uso). A partir daí, você pode alterar a sua configuração como desejar.");
$faq[] = array("A data e hora estão erradas!", "A data e hora provavelmente estão corretas, porém pode acontecer que você veja as horas em um fuso horário diferente de onde você normalmente se encontra ou inicialmente programou. Se esse é o seu caso, você deve alterar no seu perfil a opção para o seu fuso horário local, ou seja, Brasil, Londres, Paris, Nova Iorque, Sidney, ou onde você estiver. Note que a mudança do fuso horário bem como a maior parte das opções de perfil, só é permitida a usuários registrados. Se você ainda não se registrou, é hora para que se registre no fórum!");
$faq[] = array("Alterei o fuso horário, mas a data e hora continuam erradas!", "Se você tem a certeza que o fuso horário que escolheu é o correto mas a hora não é a real, é possível que seja devido a mudança horária para ajustamento de hora diurna e noturna (ou horário de verão/inverno). O phpBB não se encontra desenhado para efetuar essas alterações automaticamente, como tal devem ser alteradas manualmente pelos usuários.");
$faq[] = array("A língua de minha nacionalidade não está na lista!", "A razão mais provável é o administrador não ter instalado esse idioma ou o phpBB ainda não ter sido traduzido para o mesmo. Peça ao administrador que instale esse pacote de idiomas e, caso não exista, você poderá criar uma nova tradução. Mais informações, consulte a página oficial do <b>Grupo phpBB</b> (clicar no link ao fundo desta página).");
$faq[] = array("Como posso exibir uma imagem abaixo do meu nome de usuário?", "Deve haver duas imagens na parte inferior de cada nome de usuário quando se vêem as mensagens - a primeira representa o rank do usuário, normalmente em forma de blocos ou estrelas indicando a quantidade de mensagens que o usuário possua e seu respectivo rank, ou o estatuto do mesmo. Abaixo dessas, poderá existir uma imagem maior conhecida como avatar, que é normalmente única ou pertencente a cada usuário. Está em decisão do administrador permitir ou não o uso de avatares, e como os usuários podem enviar estas imagens. Se você não consegue enviar o seu, então possivelmente é decisão do administrador, tendo configurado o sistema para não o permitir. Pergunte-lhe a razão (temos certeza que existe uma boa resposta!).");
$faq[] = array("Como posso alterar o meu rank?", "De uma forma geral, o usuário normal não pode alterar diretamente o seu rank (os ranks aparecem por debaixo do nome de usuário em tópicos e no perfil, dependendo da template em uso). A maior parte dos ranks existentes indicam o número de mensagens enviadas ou indicam certos tipos de usuários, ou seja, moderadores e administradores poderão ter um rank especial. Por favor, não abuse do fórum enviando mensagens desnecessárias apenas para aumentar o seu nível de rank, pois os administradores ou moderadores poderão tomar alguma atitude contra você, caso verifiquem que esteja abusando.");
$faq[] = array("Quando clico no email de um usuário, uma página aparece solicitando que eu faça o login!?", "Desculpe, mas apenas usuários registrados poderão enviar email a pessoas através do formulário exclusivo do fórum (caso o administrador tenha ativado essa função). Isso é para evitar o uso malicioso do sistema de email por usuários anônimos.");


$faq[] = array("--","Sobre as <i>mensagens</i>");
$faq[] = array("Como posso enviar uma mensagem?", "Isso é fácil, clique no botão respectivo tanto no fórum como no tópico onde se encontre (dependendo da template em uso, mas normalmente os botões têm a designação de 'Nova mensagem', 'Novo tópico' ou 'Responder'). Talvez seja necessário o seu registro no fórum para poder enviar mensagens. Existe uma lista de ações que lhe são permitidas, haja registro ou não, na parte inferior do lado direito da página de cada fórum (<i>Enviar mensagens, Votar em enquetes,</i> etc.).");
$faq[] = array("Como posso editar ou excluir uma mensagem?", "A menos que seja um administrador ou moderador, você apenas pode editar ou excluir as suas próprias mensagens. Você pode editar uma mensagem (por vezes apenas por um período limitado após ser enviada) clicando no botão <i>editar</i> na parte superior da mensagem (dependendo da template em uso). Caso alguém já tenha respondido a essa mensagem, você encontrará um pequeno texto ao fundo, mencionando que foi editada e eventualmente quantas vezes. Isto não aparece apenas caso essa mensagem ainda não tenha respostas. Também não aparecerá caso a alteração seja efetuada por algum administrador ou moderador (possivelmente eles deixarão uma mensagem dizendo o que foi alterado e o motivo). Note que usuários normais não podem excluir uma mensagem após alguém já ter enviado uma resposta.");
$faq[] = array("Como posso adicionar assinatura a uma mensagem?", "Para adicionar uma assinatura a suas mensagens, você deverá primeiro criar uma em seu perfil no respectivo local. Uma vez criada, você poderá configurar o fórum, também em perfil, para 'Sempre Anexar Minha Assinatura' às mensagens ou enviá-la apenas quando quiser, selecionando anexar sua assinatura na lista de opções abaixo da caixa do envio de mensagem.");
$faq[] = array("Como posso adicionar uma enquete?", "Criar uma enquete é fácil. Quando você envia um novo tópico (ou edita a primeira mensagem de um tópico, caso tenha permissão para tal), encontra na parte inferior à caixa principal da mensagem, um painel com o título <i>Adicionar uma enquete</i> (se você não ver isto, é porque provavelmente não possui permissão para criar enquetes ou o tópico não é de sua autoria). Você deve escrever um título para a enquete e em seguida, escrever pelo menos duas opções de voto (para adicionar uma opção de voto, escreva o que pretende, e clique no botão <i>Adicionar opção de voto</i>'). Você deverá também estipular um tempo limite para a enquete, sendo 0 ilimitado. Poderá acontecer de existir um limite no número de opções de voto, estando esse limite ao critério e configuração do administrador.");
$faq[] = array("Como posso editar ou excluir uma enquete?", "Da mesma forma que as mensagens, as enquetes apenas poderão ser editadas pelo seu autor, moderadores ou administradores do fórum. Para editar uma enquete, clique na primeira mensagem do tópico (esta mensagem é a que tem a enquete associada ao tópico). Caso ninguém tenha submetido voto, os seus autores podem excluir a enquete ou editar as suas opções de voto. Contudo, se os usuários já submeteram votos, apenas moderadores e administradores podem editar ou excluir essa enquete. Isso é para evitar com que sejam alteradas as opções de voto de enquetes em curso.");
$faq[] = array("Por que não consigo entrar em um fórum?", "O acesso a alguns fóruns poderá estar limitado apenas a determinados usuários ou grupos. Para ver, ler, enviar mensagens, etc., você precisa de uma autorização especial. Apenas o moderador desse fórum e um administrador podem permitir esse acesso. Entre em contato, caso julgue necessário.");
$faq[] = array("Por que não posso votar?", "Apenas usuários registrados podem submeter os seus votos (para impedir duplicação nos resultados). Caso você esteja registrado, mas mesmo assim não consiga votar, então possivelmente não lhe foi atribuida permissão para tal.");


$faq[] = array("--","Sobre os <i>formatos</i> e <i>tipos de tópicos</i>");
$faq[] = array("O que é BBCode?", "O BBCode é uma implementação especial do HTML. A possibilidade de se usar BBCode nas suas mensagens é determinada pelo administrador do fórum. Adicionalmente, você poderá desativar o BBCode em cada mensagem, selecionando desativar o BBCode em sua mensagem abaixo da caixa principal de cada mensagem. BBCode por si mesmo é similar em estilo ao HTML, as etiquetas (tags) são incluidas em colchetes, como por <b>[exemplo]</b>, ao invés de &lt;exemplo&gt;, proporcionando uma maior facilidade na formatação de seus textos e mensagens dentro do fórum. Para mais informações, consulte o guia de BBCode, acessível no painel do envio de mensagens.");
$faq[] = array("Posso usar HTML?", "Depende se o administrador o permita, ele possui o controle completo sobre isso. Se lhe é permitido utilizar HTML, então provavelmente apenas alguns códigos lhe são acessíveis. Isto é uma medida de segurança para evitar que usuários abusem do fórum usando códigos que possam destruir o seu formato ou causar outros problemas. Caso o HTML esteja ativo, você pode desativá-lo em cada mensagem selecionando a opção de desativar HTML na mensagem.");
$faq[] = array("O que são smileys?", "Os smileys, ou emoctions, são pequenas representações gráficas que podem ser usadas para expressar algum sentimento utilizando poucos caracteres, ou seja, :) quer dizer feliz, :( quer dizer triste. Uma lista completa de smileys pode ser vista no formulário junto à caixa de cada mensagem. Tente evitar o uso excessivo dos smileys, já que podem tornar uma mensagem ilegível, podendo o administrador ou um moderador excluí-los ou deletar a mensagem inteira.");
$faq[] = array("Posso exibir imagens?", "As imagens em geral, podem ser exibidas em suas mensagens. Porém, não existe atualmente qualquer forma de armazenar imagens localmente com o phpBB, e então, você não pode exibir imagens salvas no seu próprio PC (a menos que possua um servidor publicamente acessível), nem imagens armazenadas sob mecanismos que requeiram autenticação, como por exemplo caixas de correio eletrónico de Hotmail ou Yahoo!, páginas protegidas por senha, etc. Para exibir uma imagem em sua mensagem, você pode utilizar as tags BBcode <i>[img]http://endereço.da.imagem.com[/img]</i>. Para mais informações, consulte o guia de BBCode acessível no painel do envio de mensagens.");
$faq[] = array("O que são anúncios?", "Os anúncios contém normalmente informações importantes e devem ser lidos logo que forem enviados. Os anúncios são automaticamente colocados no topo de cada página de cada fórum onde são postados. Se você pode ou não utilizar essa função, depende das permissões que lhe foram dadas e configuradas pelo administrador.");
$faq[] = array("O que são tópicos fixos?", "Os tópicos fixos aparecem abaixo dos anúncios, e apenas na primeira página de cada fórum. São tópicos com conteúdo importante e devem ser lidos logo que enviados. Da mesma forma que os anúncios, está ao critério do administrador determinar as permissões necessárias para enviar tópicos fixos em cada fórum.");
$faq[] = array("O que são tópicos trancados?", "Os tópicos trancados são assim colocados por um administrador, ou moderador de cada fórum. Quando um tópico se encontra trancado, os usuários do fórum não podem mais respondê-lo, e qualquer enquete em curso, logo será finalizada. Apenas administradores e moderadores podem responder nestes tópicos. Algum determinado tópico pode ser trancado por diversos motivos.");


$faq[] = array("--","Sobre os <i>níveis de usuários</i> e <i>grupos</i>");
$faq[] = array("O que são administradores?", "Os administradores são os usuários com o nível máximo de controle sobre todos os aspectos do fórum. Podem controlar toda a operação dos fóruns, incluindo criar, editar ou excluir fóruns, determinar permissões, banir usuários, criar grupos de usuários ou moderadores, etc. E ainda possuem todos os poderes de um moderador em todas os fóruns existentes.");
$faq[] = array("O que são moderadores?", "Os moderadores são os usuários (ou grupos de usuários) em que seu trabalho é supervisionar diariamente o andamento dos fóruns que lhes estejam designados. Eles possuem o poder de editar ou excluir mensagens, trancar, destrancar, mover e subdividir tópicos nos fóruns onde são moderadores. Geralmente os moderadores fiscalizam mensagens que possam ir <i>além do assunto em discussão</i> ou o uso de material abusivo e/ou ofensivo.");
$faq[] = array("O que são grupos de usuários?", "Os grupos de usuários são uma forma dos administradores agruparem os usuários. Cada usuário pode pertencer a vários grupos (isto difere da maioria dos outros tipos de quadros de mensagens) e a cada grupo podem ser atribuidos direitos de acesso individuais. Isto torna mais fácil aos administradores destinar vários usuários como moderadores de um determinado fórum ou dar-lhes acesso a um fórum privado, etc.");
$faq[] = array("Como me inscrevo em um grupo de usuários?", "Para se inscrever em um grupo de usuários, clique no link relativo no topo da página (dependendo da template em uso), podendo então ver todos os grupos existentes. Nem todos os grupos possuem um <i>acesso aberto</i>, alguns estão fechados e alguns poderão inclusive encontrar-se invisíveis. Se o grupo se encontrar aberto, você poderá solicitar sua inscrição clicando no botão apropriado. O moderador do grupo precisará aprovar a sua inscrição, podendo perguntar-lhe o motivo do mesmo. Por favor, não insista ao moderador do grupo caso a sua inscrição seja recusada. Ele deverá informá-lo a respeito de qualquer decisão.");
$faq[] = array("Como posso ser moderador de um grupo?", "Os grupos de usuários são inicialmente criados pelo administrador do fórum, o qual encarrega alguém de ser responsável pelo mesmo, no caso, o moderador do grupo. Se está interessado em criar um grupo de usuários, você deverá primeiramente contatar o administrador, ao qual deverá contatar com uma mensagem particular circunstanciada.");


$faq[] = array("--","Sobre as <i>mensagens particulares</i>");
$faq[] = array("Não consigo enviar mensagens particulares!", "Existem três razões para que tal possa acontecer: Você não está registrado no fórum e/ou não se encontra online, o administrador terá desativado a opção de mensagens particulares em todo o fórum ou o impede por algum motivo de enviar mensagens. Se este último é o seu caso, então você deverá perguntar ao administrador qual o motivo, caso realmente não saiba.");
$faq[] = array("Recebo mensagens particulares indesejáveis!", "Futuramente, iremos adicionar a possibilidade da existência de uma lista de usuários a serem ignorados no sistema de mensagens particulares. Por enquanto, caso você continue a receber mensagens particulares não desejadas, informe o administrador que poderá proibir o determinado usuário de enviar mensagens particulares.");
$faq[] = array("Recebi de alguém neste fórum mensagens de email com assuntos irrelevantes ou abusivos!", "Embora o sistema de emails deste fórum possuir funções de segurança que tentem detectar usuários que enviem este tipo de mensagens, lamentamos que tal tenha acontecido. Você deve informar o acontecido ao administrador do fórum com uma cópia completa do email recebido, sendo muito importante que inclua os cabeçalhos (nestes encontram-se os detalhes do usuário que enviou o email). O administrador poderá então agir em conformidade.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","Sobre o <i>sistema phpBB2</i>");
$faq[] = array("Quem escreveu o phpBB?", "Este software é produzido, publicado e com direitos reservados por <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Está disponível sob a licensa <b>GNU</b> '<i>General Public Licence</i>' e pode ser distribuido gratuitamente. Verifique o link para mais informações.");
$faq[] = array("Quem traduziu o phpBB?", "O phpBB foi traduzido por <a href=\"http://www.suportephpbb.org/\" target=\"_blank\">Suporte phpBB</a>, sendo esta tradução gratuita e disponível no link anterior. A tradução do Suporte phpBB é a oficial à Lingua Portuguesa do Brasil. Para mais informações, visite o Suporte phpBB!");
$faq[] = array("Porque não há a função X", "Este software foi escrito e licenciado pelo Grupo phpBB. Se pensa que alguma função pode ser adicionada, visite a nossa página oficial no phpBB.Com e veja o que o Grupo phpBB pode dizer sobre o assunto. Por favor, não envie mensagens com pedidos de funções na comunidade em phpBB.Com, o grupo utiliza a sourceforge para resolver situações relacionadas com funções novas. Por favor, leia cuidadosamente esse sistema para ver se alguma posição já foi tomada por nós para a função em questão, seguindo então o procedimento lá mencionado.");
$faq[] = array("Contatos sobre questões abusivas e/ou ilegais relacionadas a este fórum", "Você deve contatar o administrador do fórum. Se você não souber quem seja, contate um dos moderadores perguntando a quem deva expor o assunto. No caso de mesmo assim não obter resposta, você deve contatar o dono do domínio ou, caso o fórum esteja hospedado em um servidor grátis (por exemplo, CJB.NET, Free Forums, Yahoo!, etc.), a gerência desse serviço. Por favor, note que o Grupo phpBB não possui absolutamente nenhum controle e não pode ser responsável sobre quando, onde e por quem este fórum é utilizado. Não existe motivo em contatar o Grupo phpBB em relação a qualquer questão legal (interrupção e desistência, de responsabilidade, comentário difamatório, etc.) não diretamente relacionado com o site phpBB.Com ou ao software discreto do phpBB por si próprio. Caso envie algum email ao Grupo phpBB acerca do uso de terceiros deste software, poderá receber uma resposta concisa ou não receber resposta alguma.");

//
// This ends the FAQ entries
//

?>
